# Load react_native_pods.rb properly
require_relative '../node_modules/react-native/scripts/react_native_pods'

# Set minimum iOS platform version
platform :ios, '16.0'

# Prepare React Native environment
prepare_react_native_project!

# Configure framework linkage (static or dynamic)
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  use_frameworks! :linkage => :static
end

# Main App Target
target 'Trendyol' do
  config = use_native_modules!

  # Firebase dependencies with modular headers
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  # React Native setup
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Test Target
  target 'TrendyolTests' do
    inherit! :complete
    # Pods for testing (you can add test dependencies here if needed)
  end

  # Post Install configuration
  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
      # :ccache_enabled => true # Uncomment if you use ccache
    )
  end
end


